name: Build & push to docker && deploy to ec2

on:
  push:
    branches:
      - main
    paths:
      - 'worker/**'
      - '.github/workflows/cd-worker.yml'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image to Docker Hub (Staging)
        uses: docker/build-push-action@v3
        with:
          context: worker
          dockerfile: worker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mvsp:worker-latest

      - name: Verify Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/mvsp:worker-latest

      - name: Deploy to STAGING EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          key: ${{ secrets.ECS_KEY }}
          script: |
           sudo docker stop mvsp-worker || true
           sudo docker rm mvsp-worker || true
           sudo docker network create mvsp-worker || true
           sudo docker pull ${{ secrets.DOCKER_USERNAME }}/mvsp:worker-latest
           sudo docker run -d \
             --name mvsp-worker \
             --network mvsp-worker \
             -v /home/ubuntu/env/mvsp-worker.env:/app/.env \
             -p 5001:5001 \
             ${{ secrets.DOCKER_USERNAME }}/mvsp:worker

           sudo docker exec mvsp-worker npx prisma migrate deploy --schema=src/prisma/schema.prisma
           sudo docker exec mvsp-worker npm run db:generate
           echo "Worker deployment completed successfully"