name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cache node_modules to speed up installation
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: cd frontend && npm install --force

      # Build the app
      - run: cd frontend && npm run build || true # Ensure the build is done before deployment

      # Cache the build folder to speed up deployments
      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: frontend/build
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-build-

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOVIEAPP_CD283 }}
          channelId: live
          projectId: movieapp-cd283

